### PR TITLE
Add a retry mechanism when pushing on remote repository

### PR DESCRIPTION
**Pull request by vrigal**
Closes [code-review#135](../../code-review/issues/135)

### CODE REVIEW

**Comment by vrigal** [comment]
@La0 Can you tell me if this approach (simple retry) seems accurate according to your comment on the Code review project ?
https://github.com/mozilla/code-review/issues/135#issuecomment-1198234804

**Comment by La0** [comment]
Not really, you need to use the internal queue system (aka BUS), adding the same payload we got as input in mercurial. I'll explain more on visio if needed

**Comment by abpostelnicu** [comment]
Feel free please to rage me for review when you think this is ready ;)

**Comment by vrigal** [comment]
I added a parameter defining the max number of retry (defaults to 1 initial + 4 retries), to eventually avoid an infinite failure pattern.

**Review by abpostelnicu — APPROVED** [review]

**Pull request merged**
